# Generated by Django 4.2.6 on 2023-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRecipe',
            fields=[
                ('recipe_id', models.IntegerField(blank=True, null=True)),
                ('recipe_name', models.TextField(blank=True, db_column='Recipe Name', null=True)),
                ('ingredients', models.TextField(blank=True, db_column='Ingredients', null=True)),
                ('cuisine', models.TextField(blank=True, db_column='Cuisine', null=True)),
                ('instructions', models.TextField(blank=True, db_column='Instructions', null=True)),
                ('totaltimeinmins', models.IntegerField(blank=True, db_column='TotalTimeInMins', null=True)),
                ('imageurl', models.TextField(blank=True, db_column='Imageurl', null=True)),
                ('ingredientcount', models.IntegerField(blank=True, db_column='Ingredientcount', null=True)),
            ],
            options={
                'db_table': 'final recipe',
                'managed': False,
            },
        ),
    ]
